version: "3"

services:
  app:
    image: csirt-backend
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    restart: on-failure
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    command: >
      bash -c "
        python manage.py migrate && \
        python manage.py collectstatic --noinput && \
        gunicorn csirt.wsgi:application -w 2 -b 0.0.0.0:8000 --reload"
    environment:
      LAUNCH_TYPE: webserver
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: csirt_db
      DB_PORT: 5432
      DB_ENGINE: django.db.backends.postgresql
    depends_on:
      - postgres
    networks:
      - csirt_network

  postgres:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=csirt_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    command: ["postgres", "-c", "max_connections=200", "-c", "timezone=Etc/UTC", "-c", "default_text_search_config=pg_catalog.english"]
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - csirt_network

volumes:
  postgres-data:

networks:
  csirt_network:
    driver: bridge
