# Generated by Django 4.1.7 on 2024-02-15 11:01

from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CERT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField()),
            ],
        ),
    ]
